apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  namespace: weavesocks
  name: weavesocks
spec:
  replicas: 1
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
  images:
    coherence:
      image: oracle/coherence:12.2.1.4.0-b74630
  logging:
    configFile: logging.properties
  maxHeap: 64m
  javaOpts: "-Dcoherence.management.http=none -Dcoherence.metrics.http.enabled=false"
  resources:
    limits:
      cpu: 2
    requests:
      cpu: 1
  roles:
    - role: catalogue
      images:
        userArtifacts:
          image: weavesocks/catalogue:1.0.0
      ports:
        - name: http
          port: 7001
          service:
            name: catalogue
            port: 80
